server:
  port: 8082

spring:
  application:
    name: e-commerce-payment-api
  datasource:
    url: jdbc:postgresql://localhost:5433/payment
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
          show_sql: true
          use_sql_comments: true
          jdbc:
            lob:
              non_contextual_creation: true
  cloud:
    stream:
      function:
        definition: checkoutCreatedEventConsumer
      bindings:
        checkoutCreatedEventConsumer-in-0:
          destination: streaming.ecommerce.checkout.created
          contentType: application/*+avro
          consumer:
            use-native-encoding: true
      binder:
        auto-create-topics: true
        brokers: localhost:9092
      kafka:
        streams:
          binder:
            configuration:
              schema.registry.url: http://localhost:8081
              specific.avro.reader: true
#app:
#  topic:
#    payment-paid: streaming.ecommerce.payment.paid
