spring:
  application:
    name: e-commerce-checkout-api
  datasource:
    url: jdbc:postgresql://localhost:5432/checkout
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
  kafka:
    producer:
      properties:
        schema.registry.url: http://localhost:8081
        allow.auto.create.topics: true
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#    consumer:
#      properties:
#        schema.registry.url: http://localhost:8081
#        specific.avro.reader: true
#        allow.auto.create.topics: true
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
app:
  topic:
    checkout-created: streaming.ecommerce.checkout.created
#    payment-paid: streaming.ecommerce.payment.paid
