spring:
  application:
    name: e-commerce-checkout-api
  datasource:
    url: jdbc:postgresql://localhost:5432/checkout
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true
  cloud:
    stream:
      function:
        definition: checkoutCreatedEventSupplier;paymentPaidEventConsumer
      bindings:
        checkoutCreatedEventSupplier-out-0:
          destination: streaming.ecommerce.checkout.created
          contentType: application/*+avro
          producer:
            use-native-encoding: true
        paymentPaidEventConsumer-in-0:
          destination: streaming.ecommerce.payment.paid
          contentType: application/*+avro
          consumer:
            use-native-encoding: true
      binder:
        auto-create-topics: true
        brokers: localhost:9092
      kafka:
        bindings:
          checkoutCreatedEventSupplier-out-0:
            producer:
              configuration:
                schema.registry.url: http://localhost:8081
                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        streams:
          binder:
            configuration:
              schema.registry.url: http://localhost:8081
              specific.avro.reader: true
